### PR TITLE
Some documentation and a small fix

### PR DESCRIPTION
**Pull request by Akendo**
Simple way of creating the API Key in MITE. Fix the code sample, because the
example has the parameter mixed up.

### CODE REVIEW

**Comment by hellerve** [comment]
Thanks so much, this is super useful! I’d like to change the title from `Pre-requirements` to `Prerequisites`, is that alright with you?

**Comment by Akendo** [comment]
Sure, feel free to change it..

**Comment by Akendo** [comment]
I made the change you ask for.

**Comment by hellerve** [comment]
Thank you again!

**Pull request merged**
